version: '3'

services:
  vue:
    build:
      context: ./vue
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
    ports:
        - "8080:8080"
    volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    tty: true